## This Action is for automation pull request on my pc server
name: Automatic pull

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Do some pull request
        shell: cmd
        env:
          TARGET_DIR: ${{ secrets.PROJECT_PATH }}
          SECRET_FOLDER: ${{ secrets.ENV_BASE_UPLOAD_FOLDER }}
          SECRET_CATEGORIES: ${{ secrets.ENV_ALLOWED_CATEGORIES }}
          SECRET_URL: ${{ secrets.ENV_BASE_PUBLIC_URL }}
          SECRET_MAX_SIZE: ${{ secrets.ENV_MAX_CONTENT_LENGTH }}
          SECRET_API_KEY: ${{ secrets.ENV_API_KEY }}
        run: |
          cd /d "%TARGET_DIR%"
          git fetch origin main
          :: pull with git reset
          git reset --hard origin/main

          ::  matikan server
          taskkill /IM python.exe /F 2>nul

          :: Rewrite secrets -> env
          (echo BASE_PUBLIC_URL=%SECRET_URL%) > .env
          (echo BASE_UPLOAD_FOLDER=%SECRET_FOLDER%) >> .env
          (echo ALLOWED_CATEGORIES=%SECRET_CATEGORIES%) >> .env
          (echo MAX_CONTENT_LENGTH=%SECRET_MAX_SIZE%) >> .env
          (echo API_KEY=%SECRET_API_KEY%) >> .env

          ::  nyalakan server
          start "" /B cmd /c "python app.py"