## This Action is for automation pull request on my pc server
name: Automatic pull

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Do some pull request
        shell: cmd
        env:
          TARGET_DIR: ${{ secrets.PROJECT_PATH }}
        run: |
          cd /d "%TARGET_DIR%"
          git pull origin main